
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_management_system?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12042004huy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ??a ch? SMTP server c?a Gmail
spring.mail.host=smtp.gmail.com
# C?ng k?t n?i (587 là c?ng tiêu chu?n cho TLS)
spring.mail.port=587

# Email c?a b?n
spring.mail.username=nguyenlenhhiep@gmail.com
# Dán 16 ký t? m?t kh?u ?ng d?ng v?a t?o vào ?ây (không ch?a d?u cách)
spring.mail.password=uwzqsqdvjhjlauui

# Các c?u hình b? sung ?? ??m b?o b?o m?t và xác th?c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
server.port=8080