
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_management_system?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12042004huy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ??a ch? SMTP server c?a Gmail
spring.mail.host=smtp.gmail.com
# C?ng k?t n?i (587 là c?ng tiêu chu?n cho TLS)
spring.mail.port=587

# Email c?a b?n
spring.mail.username=nguyenlenhhiep@gmail.com
# Dán 16 ký t? m?t kh?u ?ng d?ng v?a t?o vào ?ây (không ch?a d?u cách)
spring.mail.password=uwzqsqdvjhjlauui

# Các c?u hình b? sung ?? ??m b?o b?o m?t và xác th?c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
server.port=8080
payos.client.id=f8e0d2fc-c03f-4f49-8931-c57cd5a4fe58
payos.api.key=c5763434-6136-402b-8aaf-0ab09a385698
payos.checksum.key=f20f7fab5562f18d11c3b648dc395a5ca4e4d78453118d2fd2bbe592c2a1c5d0
spring.mail.properties.mail.smtp.ssl.trust=*
# Hi?n th? n?i dung tin nh?n l?i trong JSON response
server.error.include-message=always

# (Tùy ch?n) Hi?n th? các l?i ràng bu?c d? li?u n?u có
server.error.include-binding-errors=always
